version: '3.8'
services:
  backend:
    build: ./backend
    container_name: panscience_backend
    restart: always
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=your_mongodb_atlas_connection_string
      - JWT_SECRET=your_jwt_secret
      - AWS_REGION=your_aws_region
      - AWS_ACCESS_KEY_ID=your_aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key
      - AWS_BUCKET_NAME=your_s3_bucket_name
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: panscience_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend